name: Telegram Bot Core Abstraction .NET package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  build:

    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "src/SkyNeg.Telegram.Bot.Abstraction.sln"
      PROJECT: "src/SkyNeg.Telegram.Bot.Abstraction/SkyNeg.Telegram.Bot.Abstraction.csproj"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

    - name: Pack Nuget
      run: dotnet pack $PROJECT --configuration $BUILD_CONFIG

    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push src/SkyNeg.Telegram.Bot.Abstraction/**/*.nupkg -k ${PUBLISHER_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols 
      env:
        PUBLISHER_TOKEN: ${{secrets.NUGET_ORG_PUBLISHER_TOKEN}}
