name: Telegram Bot Core Abstraction .NET package

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    env:
      BUILD_CONFIG: "Release"
      SOLUTION: "src/SkyNeg.Telegram.Bot.Abstraction.sln"
      PROJECT: "src/SkyNeg.Telegram.Bot.Abstraction/SkyNeg.Telegram.Bot.Abstraction.csproj"

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet build ${{ env.SOLUTION }} --configuration  ${{ env.BUILD_CONFIG }} --no-restore

    - name: Pack Nuget
      run: dotnet pack ${{ env.PROJECT }} --configuration  ${{ env.BUILD_CONFIG }}

    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push src/SkyNeg.Telegram.Bot.Abstraction/**/*.nupkg -k ${{ env.PUBLISHER_TOKEN }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols 
      env:
        PUBLISHER_TOKEN: ${{secrets.NUGET_ORG_PUBLISHER_TOKEN}}
